.TH "tumb" 1 "April 2012" "Version 0.1" "User Commands"
.SH NAME
tumb \- tumblr theme deployer
.SH SYNOPSIS
.B tumb
\fIusername\fR \fIpassword\fR \fIblog\fR
.SH DESCRIPTION
.B tumb
is a ruby program that automates the process of deploying themes to Tumblr.
.SH CONFIGURATION
The 
.B tumb
command requires the following dependencies to be installed on your machine.
.sp
\h'-04'\(bu\h'+03'\c
.B ruby
1.9.2 or above
.sp
\h'-04'\(bu\h'+03'\c
.B mechanize
gem
.sp
To install mechanize, you can use the 
.B gem
command.
.sp
.B gem install mechanize
.SH AUTHOR
Written by Rainer Borene.
.SH "REPORTING BUGS"
Report bugs to <https://github.com/rainerborene/tumb/issues/>
.SH "SEE ALSO"
.BR ruby (1),
.BR gem (1)
